### ISSUE TITLE
Create `Filter`

### ISSUE THREAD

**Issue by ggogobera** [darsal03/PROJECT#30]
A `Filter` component that will be fixed on top after the header.

It should be a full width, 80-100px height bar with corresponding items.

It must contain:
* Sort button (change `asc` and `desc` order on click)
* Date from picker
* Date to picker
* Time from picker
* Time to picker

Use [Material](https://mui.com/) [pickers](https://mui.com/components/pickers/#main-content). Use `date-fns` with date adapter.

**Comment by darsal03** [comment]
ეხლა ბექზე დავფიქსე find ქუერი (იდეა შენი მეთოდიდან ავიღე,query object მაქ,და პარამეტრების მიხედვით ვცვლი მაგ ობჯექთს)

let-ს გამოყენება ამ შემთხვევაში ხომ დასაშვებია?
![code](https://user-images.githubusercontent.com/68153140/149832871-acd33a49-2c79-46db-81a3-62c3eec603f9.png)

asc და desc კალორიების მიხედვით,თუ დროის? 

date-time picker-ი რომ ავიღო ხომ აჯობებს, დეითიც აქვს და საათი/წუთებიც

**Comment by ggogobera** [comment]
let მოსულა, რა თქმა უნდა.

Date time picker ერთიანი რომ აიღო დავალებას ვერ შეასრულებ. საწყისი და საბოლოო დრო არ მინდა. მინდა დიაპაზონი. 

თარიღის და საათის

**Comment by darsal03** [comment]
ზემოთ რა კოდიც მაქ იქ ეგრე გამოდის ,რომ ასიანი ორივე უნდა მიუთითოს (დასაწყი და დასასრული საათი თუ დეითი მნიშვნელობა არააქ),ეგრე ხომ არ გვინდა ,ანუ მარტო რომ მიუთითოს 23 რიცხვიდან,უნდა აჩვენოს 23იდან ზემოთ.

im limiting the user ეგრე არ გამოდის?  not that big of a deal არის, თუ code warcrime

**Comment by ggogobera** [comment]
მარტო 23-დან რომ მიუთითოს უნდა გამოჩნდეს ყველა თვეების ჩანაწერი 23-დან. 

day gte 23

კოდი გადასაკეთებელია მაშინ
