### ISSUE TITLE
Create auth controller methods for authentication

### ISSUE THREAD

**Issue by ggogobera** [darsal03/PROJECT#8]
We will store sessions in the MongoDB. Authentication should be leveraged by express-session.

- [ ] Set up `express-session`. Set `resave` and `saveUninitialized` to false which are useful for auth
- [ ] Use [MongoDBSession](https://github.com/jdesboeufs/connect-mongo) for `store`
- [ ] Change `/users` post route to use session
- [ ] Create `/login` route with appropriate controller method
- [ ] Create `/logout` route with appropriate controller method
- [ ] Create `/authenticate` middleware for future use to forbid access to some routes

**Comment by darsal03** [comment]
ok ,my bad
